[Variables]
; Appearance
height=25
width=120
orient=LEFT

BGColor1=20,20,20,200
BGColor2=10,10,10,200

CircleColor1=60,179,113
CircleColor2=153,50,204

TextColor1=218,112,214
TextColor2=218,112,214

TextH1=9
TextH2=7

; Info
Drive1=C
Drive2=D
Drive3=H

MediaPlayer=VLC

DLSpeed=3000000
ULSpeed=1000000

BinMax=1000000000

TimeFormat=%#I:%M %p
DateFormat=%a, %#d %B

wCode=USTX0057
wUnit=f
